[package]
name = "erlcuda_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "erlcuda_nif"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustler = "0.38"
cust = { git = "https://github.com/Rust-GPU/rust-cuda", rev = "6a836d9236fc38e0fa7a71f7bdeda7a8f82bc8d5" }
cust_raw = { git = "https://github.com/Rust-GPU/rust-cuda", rev = "6a836d9236fc38e0fa7a71f7bdeda7a8f82bc8d5", default-features = false, features = ["driver"] }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/rust-cuda", rev = "6a836d9236fc38e0fa7a71f7bdeda7a8f82bc8d5", default-features = false }
